### ISSUE TITLE
Wrong year input breaks current year to be input as a date

### ISSUE THREAD

**Issue by vlAsTT** [tormozz48/football-chat-bot-2#58]
Reproduction steps;

1. Create a new event with not a current year (e.g. 03-04-2024)
2. Next time you try to create event with a current year (e.g. 05-04-2023), you are getting an empty response:
`{}`
3. If you try to add/remove people from the event, response is: `Event entry is not found`

Removing the bot and adding to the chat back doesn't help, same as deleting chat history and setting auto-delete every N days. 
From that moment, it's possible to create an event only for a year bigger than the one in the wrong date (if I make an event for 03-04-2023, since then I can only do year >=2024, 2023 will give me an empty response).

**Comment by tormozz48** [comment]
Hello @vlAsTT.

Thank your for your feedback.

Actually bot implementation is in another repo: https://github.com/tormozz48/football-chat-bot-aws. I made implementation based on AWS Lambda functions year ago.

However your post motivated me to fix this weird issue. 
Now it should allow to create events with earlier dates than created before.

Some technical details.

I was wrong dealing with DynamoDB API. I loaded last active event with `Limit: 1` and query like:
```ts
{
    KeyConditionExpression: 'chatId = :c',
    FilterExpression: 'active = :a',
    ExpressionAttributeValues: {
      ':c': chatId,
      ':a': 1,
    },
  }
```

> A FilterExpression is applied after the items have already been read; the process of filtering does not consume any additional read capacity units.

So in case when latest record is not active, this query returns empty result which cause your problem. Now it should be OK.
